baseURL                   = "https://www.joeroccio.com"
builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "docs"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 80
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Joseph Roccio"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"

[[menu.main]]
    name                   = "About Me"
    weight                 = -100
    identifier             = "about"
    url                    = "about"

[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"



  
  [[menu.main]]
    name = "Resume"
    identifier = "resume"
    weight = -100
    url = "https://github.com/timeharvest/joe/raw/master/static/resume.pdf"  

 

[params]


  navtabimg                = "img/joboi.png"
  faviconfile              = "img/zheng.png"               # from static/
  avatar                   = "img/profile.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Joseph Roccio "
  description              = ["Be myself.", "Love the wonderful world.", "Chemical Engineer Extraordinaire."]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "~ No Day But Today ~"

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "josephroccio@gmail.com"
  #github                   = "//github.com/you"
  linkedin                 = "//linkedin.com/in/jroccio"
  #facebook                 = "//facebook.com/you"
  #googleplus               = "//google.com/you"
  #twitter                  = "//twitter.com/you" 
  #px500                    = "//px500"
  #instagram                = "//instagram.com/you"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    
  